### PR TITLE
Fix InvalidCastException when hosting an ASP.NET Core behind Azure Relay

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
fixes https://github.com/Azure/azure-relay-aspnetserver/issues/10

/cc  @Tratcher

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
@Tratcher do you have some ETA for this bug fix release to https://www.nuget.org/packages/Microsoft.Azure.Relay.AspNetCore/?

**Comment by Tratcher** [comment]
No idea, I don't actually work on this project, the code was copied from one I do work on.

@clemensv ?

**Comment by MarcoRossignoli** [comment]
@clemensv @pranavkm any news?
Do you think is better clone code an merge with my codebase or is there a plan to push rtm package(now i get a lot of warning message from build related to references)?

**Comment by MarcoRossignoli** [comment]
Sorry guys...any news on this?
/cc @Tratcher @clemensv @davidfowl @pranavkm

**Pull request merged**
